import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import MyNav from "@/components/myNav";
import { Fragment } from "react";

import 'react-tabulator/lib/styles.css';
import { ReactTabulator } from 'react-tabulator'


export default function About(){

    return (
        <Fragment>        
        <MyNav/>
        <h1>Hello world</h1>
        </Fragment>

    )
}